parameters:
#    mastercel_chart.example.class: Mastercel\ChartBundle\Example

services:
#    mastercel_chart.example:
#        class: %mastercel_chart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
